// src/components/BarcodeReader.vue
<script setup lang="ts">
import { onMounted, ref } from "vue";

const video = ref<HTMLVideoElement>();
const barcodes = ref<string[]>([]);

onMounted(async () => {
  if (!video.value) return;

  video.value.srcObject = await navigator.mediaDevices.getUserMedia({
    audio: false,
    video: {
      facingMode: "environment", // 背面カメラ
    },
  });
});

setInterval(async () => {
  if (!video.value || barcodes.value.length) return;

  const detector = new (window as any).BarcodeDetector({ formats: ["ean_13"] });
  const result: any[] = await detector.detect(video.value);

  if (result.length) {
    barcodes.value = result.map((v) => v.rawValue);
    video.value.pause();
  }
}, 1000);

const reset = () => {
  barcodes.value = [];
  video.value?.play();
};
</script>

<template>
  <video ref="video" width="240" autoplay />

  <ul>
    <li v-for="v in barcodes" :key="v">
      <a :href="`https://www.amazon.co.jp/s?k=${v}`" target="_blank">
        barcode: {{ v }}
      </a>
    </li>
  </ul>

  <button v-show="barcodes.length" @click="reset()">reset</button>
</template>

<style scoped>
video {
  display: block;
  margin: 0.75rem auto;
}
</style>

// src/components/BarcodeReader.tsx
import { useEffect, useRef, useState } from "preact/hooks";
import style from "./BarcodeReader.module.css";

export function BarcodeReader() {
  const video = useRef<HTMLVideoElement>(null);
  const [barcodes, setBarcodes] = useState<string[]>([]);

  // カメラ入力を video に
  useEffect(() => {
    if (!video.current) return;

    navigator.mediaDevices
      .getUserMedia({
        audio: false,
        video: {
          facingMode: "environment", // 背面カメラ
        },
      })
      .then((stream) => {
        if (!video.current) return;
        video.current.srcObject = stream;
      });
  }, [video]);

  // video からバーコード読み取り
  useEffect(() => {
    if (!video.current || barcodes.length) return;

    const timerId = setInterval(async () => {
      if (!video.current) return;

      const detector = new (window as any).BarcodeDetector({
        formats: ["ean_13"],
      });
      const result: any[] = await detector.detect(video.current);

      if (result.length) {
        setBarcodes(result.map(({ rawValue }) => rawValue));
        video.current.pause();
      }
    }, 1000);

    return () => clearInterval(timerId);
  }, [video, barcodes]);

  const reset = () => {
    setBarcodes([]);
    video.current?.play();
  };

  return (
    <>
      <video ref={video} class={style.video} width="240" autoPlay />

      <ul>
        {barcodes.map((code) => (
          <li key={code}>
            <a
              href={`https://www.amazon.co.jp/s?k=${code}`}
              target="_blank"
              rel="noreferrer"
            >
              {code}
            </a>
          </li>
        ))}
      </ul>

      <button onClick={reset} disabled={!barcodes.length}>
        reset
      </button>
    </>
  );
}
